const birds = [
  {
    sciName: "Struthio camelus",
    comName: "Common Ostrich",
    speciesCode: "ostric2",
    category: "species",
    taxonOrder: 2.0,
    bandingCodes: [],
    comNameCodes: ["COOS"],
    sciNameCodes: ["STCA"],
    order: "Struthioniformes",
    familyCode: "struth1",
    familyComName: "Ostriches",
    familySciName: "Struthionidae",
  },
  {
    sciName: "Struthio molybdophanes",
    comName: "Somali Ostrich",
    speciesCode: "ostric3",
    category: "species",
    taxonOrder: 7.0,
    bandingCodes: [],
    comNameCodes: ["SOOS"],
    sciNameCodes: ["STMO"],
    order: "Struthioniformes",
    familyCode: "struth1",
    familyComName: "Ostriches",
    familySciName: "Struthionidae",
  },
  {
    sciName: "Branta canadensis moffitti/maxima",
    comName: "Canada Goose (moffitti/maxima)",
    speciesCode: "cangoo4",
    category: "issf",
    taxonOrder: 320.0,
    bandingCodes: ["LCGO"],
    comNameCodes: ["CANG", "CAGO"],
    sciNameCodes: ["BRCA"],
    order: "Anseriformes",
    familyCode: "anatid1",
    familyComName: "Ducks, Geese, and Waterfowl",
    familySciName: "Anatidae",
    reportAs: "cangoo",
  },
  {
    sciName: "Branta canadensis occidentalis/fulva",
    comName: "Canada Goose (occidentalis/fulva)",
    speciesCode: "cangoo3",
    category: "issf",
    taxonOrder: 323.0,
    bandingCodes: [],
    comNameCodes: ["CANG", "CAGO"],
    sciNameCodes: ["BRCA"],
    order: "Anseriformes",
    familyCode: "anatid1",
    familyComName: "Ducks, Geese, and Waterfowl",
    familySciName: "Anatidae",
    reportAs: "cangoo",
  },
  {
    sciName: "Branta canadensis [canadensis Group]",
    comName: "Canada Goose (canadensis Group)",
    speciesCode: "cangoo1",
    category: "issf",
    taxonOrder: 326.0,
    bandingCodes: [],
    comNameCodes: ["CANG", "CAGO"],
    sciNameCodes: ["BRCA"],
    order: "Anseriformes",
    familyCode: "anatid1",
    familyComName: "Ducks, Geese, and Waterfowl",
    familySciName: "Anatidae",
    reportAs: "cangoo",
  },
];
module.exports = birds;
